
- hosts: servers
  gather_facts: True
  vars_files:
      - vars.yml


  #
  # Tasks
  #

  tasks:

      - name: Show ansible version
        debug:
            msg: "ansible_version: {{ansible_version.major}}"

      - name: Check ansible version
        fail:
            msg: "This playbook requires Ansible 2.x or greater."
        when: ansible_version.major < 2

      #
      # Packages
      #

      - name: Install required packages.
        become: true
        apt:
            pkg: "{{item}}"
            state: present
            update_cache: "{{apt_update_cache}}"
        with_items: "{{project_packages}}"

      #
      # User
      #

      - name: Add group
        become: true
        group:
            name: "{{usergroup}}"

      - name: Add user
        become: true
        user:
            name: "{{username}}"
            group: "{{usergroup}}"
            home: "{{home}}"
            shell: /bin/bash
            generate_ssh_key: no
            state: present
            #password: "{{user_password}}"

      - name: Create standard folders
        become: true
        file:
            path: "{{item}}"
            state: directory
            owner: "{{username}}"
            group: "{{usergroup}}"
        with_items:
          - "{{home}}/logs"
          - "{{home}}/run"
          - "{{home}}/public"
          - "{{home}}/public/static"
          - "{{home}}/public/media"

      - name: Create project folder with restricted permissions
        become: true
        file:
            path: "{{item}}"
            state: directory
            owner: "{{username}}"
            group: "{{usergroup}}"
            mode: 0750
        with_items:
          - "{{home}}/{{project_name}}"

      #
      # Project
      #

      - name: Pull sources from the repository.
        become: true
        become_user: "{{username}}"
        git:
            repo: "{{project.repo}}"
            dest: "{{project.website_root}}/"
            version: "{{version}}"
            accept_hostkey: True
            force: True
        notify:
            - Restart Nginx
            - Restart supervised services
        tags: quick

      - name: Adjust settings for production
        become: true
        become_user: "{{username}}"
        lineinfile:
            path: "{{project.settings_file}}"
            regexp: "{{ item.regexp }}"
            line: "{{ item.line }}"
        with_items:
            - { regexp: '^DEBUG =', line: 'DEBUG = False' }
            - { regexp: '^COMPRESS_ENABLED =', line: 'COMPRESS_ENABLED = False' }
            - { regexp: '^ALLOWED_HOSTS =', line: 'ALLOWED_HOSTS = ["localhost", "127.0.0.1", "{{ inventory_hostname }}"]' }
            - { regexp: '^MEDIA_ROOT =', line: 'MEDIA_ROOT = "{{project.media_root}}"' }
            - { regexp: '^STATIC_ROOT =', line: 'STATIC_ROOT = "{{project.static_root}}"' }
            - { regexp: '^CHANNEL_PREFIX =', line: 'CHANNEL_PREFIX = "{{project_instance}}:"' }
        tags: quick


      - name: Remove pyc files
        become: true
        become_user: "{{username}}"
        command: find . \( -name \*.pyc -o -name \*.pyo -o -name __pycache__ \) -prune -exec rm -rf {} +
        args:
          chdir: "{{project.website_root}}"
        tags: quick

      - name: Create "setenv" script
        become: true
        become_user: "{{username}}"
        template:
            src: deployment/project/setenv.bash
            dest: "{{project.root}}"

      - name: Upgrade the virtualenv
        become: true
        become_user: "{{username}}"
        pip:
            virtualenv={{project.virtualenv}}
            virtualenv_python={{virtualenv_python}}
            requirements={{project.website_root}}/requirements.txt
        #ignore_errors: yes
        tags: quick

      - name: Run django management commands
        become: true
        become_user: "{{username}}"
        django_manage:
            command: "{{item}}"
            app_path: "{{project.website_home}}"
            settings: "{{project_name}}.settings"
            virtualenv: "{{project.virtualenv}}"
            pythonpath: "{{project.pythonpath}}"
        with_items:
            "{{project.management_commands}}"
        tags: quick

      - name: Install Nginx configuration file
        become: true
        template:
            src: deployment/project/nginx.conf
            dest: /etc/nginx/sites-available/{{project_instance}}.conf
        notify:
            - Restart Nginx

      - name: Enable nginx configuration file
        become: true
        file:
            src: /etc/nginx/sites-available/{{project_instance}}.conf
            dest: /etc/nginx/sites-enabled/{{project_instance}}.conf
            state: link
        notify:
            - Restart Nginx

      - name: Create Supervisord configuration file
        become: true
        template:
            src: deployment/project/supervisor.conf
            dest: /etc/supervisor/conf.d/{{project_instance}}.conf
        notify:
          - Add supervised services
          - Restart Nginx

      - name: Create logrotate configuration file
        become: true
        template:
            src: deployment/project/logrotate.conf
            dest: "/etc/logrotate.d/{{project_instance}}"

  #
  # Handlers
  #

  handlers:

      - name: Restart Nginx
        become: true
        service:
            name: nginx
            state: restarted

      - name: Reload Nginx
        become: true
        service:
            name: nginx
            state: reloaded

      - name: Restart Redis
        become: true
        service:
            name: redis-server
            state: restarted

      - name: Add supervised services
        become: true
        supervisorctl:
            name: "{{item}}"
            state: present
        with_items:
            "{{supervised_services}}"
        notify:
            - Restart supervised services

      # When state = restarted,
      #     the module will call supervisorctl update then call supervisorctl restart.
      #
      - name: Restart supervised services
        become: true
        supervisorctl:
            name: "{{item}}"
            state: restarted
        with_items:
            "{{supervised_services}}"
